#!/bin/sh
#
# If the $FLAG is set, make "at-boot" the default target.
#

FLAG=/at-boot
ATBOOT=/lib/systemd/system/at-boot.target
DEFAULT=/run/systemd/system/default.target

test -x $FLAG && ln -sf $ATBOOT $DEFAULT
true
